[package]
name = "panorama-maildir"
version = "0.1.0"
authors = ["Michael Zhang <mail@mzhang.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0.39"
futures = "0.3.13"
tempfile = "3.2.0"
tokio = { version = "1.3.0", features = ["full"] }
