[package]
name = "panorama-imap"
version = "0.0.1"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>", "Michael Zhang <mail@mzhang.io>"]
description = "IMAP protocol parser and data structures"
keywords = ["imap", "email"]
categories = ["email", "network-programming", "parser-implementations"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
anyhow = "1.0.38"
tokio = { version = "1.1.1", features = ["full"] }
futures = "0.3.12"
nom = { version = "6.1.2", default-features = false, features = ["std"] }
derive_builder = "0.9.0"
tokio-rustls = "0.22.0"
webpki-roots = "0.21.0"
panorama-strings = { path = "../strings", version = "0" }
parking_lot = "0.11.1"
tracing = "0.1.23"

[dev-dependencies]
assert_matches = "1.3"
