on: [push]

name: build-deb

jobs:
  build_deb:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: build-deb
        run: |
          cargo install cargo-deb
          cargo deb
      - uses: actions/upload-artifact@v2
        with:
          name: panorama.deb
          path: target/debian/panorama*.deb

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo

# vim: set ts=2 tw=2 sw=2 et :
