on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: build mdbook
        run: |
          mdbook build docs -d $(pwd)/public

      - name: build api docs
        run: |
          cargo doc --workspace --no-deps --document-private-items
          cp -r target/doc public/api

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public

# vim: set sw=2 tw=2 :
