on: [push]

name: run-tests

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: |
          cargo test --all

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo

# vim: set ts=2 tw=2 sw=2 et :
